#### Render Blueprint specification: https://dashboard.render.com/blueprints ####
## 👇 Preview environments: https://render.com/docs/preview-environments ###
# previewsEnabled: true
## 👇 Automatically nuke the environment after X days of inactivity to reduce billing:
# previewsExpireAfterDays: 2
services:
  - type: web
    name: zipper-functions
    env: node
    plan: free
    ## 👇 Specify the plan for the PR deployment:
    # previewPlan: starter
    ## 👇 Preview Environment Initialization script:
    # initialDeployHook: yarn db-seed
    buildCommand: yarn install; yarn build
    startCommand: PORT=443 yarn start:production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zipper-functions-db
          property: connectionString

databases:
  - name: zipper-functions-db
    plan: free
