previewsEnabled: true
previewsExpireAfterDays: 2

services:
  # # # ZIPPER.DEV # # #
  - type: web
    name: zipper.dev--preview
    runtime: node
    # # #
    plan: free
    previewPlan: starter
    # # #
    rootDir: apps/zipper.dev
    buildFilter:
      paths:
        - apps/zipper.dev/**/*
        - packages/**/*
      ignoredPaths:
        - '**/*.test.ts'
        - '**/*.test.tsx'
    initialDeployHook: 'yarn db-migrate-dev; yarn db-seed'
    buildCommand: 'yarn install; yarn env:inject:preview -- -- yarn build'
    startCommand: 'yarn start:preview'
    # # #
    envVars:
      - fromGroup: zipper-env-group--preview
      - key: DATABASE_URL
        fromDatabase:
          name: zipper-db--preview
          property: connectionString
      - key: REDIS_HOST
        fromService:
          type: redis
          name: zipper-redis--preview
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: zipper-redis--preview
          property: port
      - key: PUBLICLY_ACCESSIBLE_RPC_HOST
        fromService:
          name: zipper.dev--preview
          type: web
          property: host
      - key: NEXT_PUBLIC_ZIPPER_DOT_DEV_HOST
        fromService:
          name: zipper.dev--preview
          type: web
          property: host
      - key: NEXT_PUBLIC_ZIPPER_DOT_RUN_HOST
        fromService:
          name: zipper.run--preview
          type: web
          property: host

  # # # ZIPPER.RUN # # #
  - type: web
    name: zipper.run--preview
    runtime: node
    # # #
    plan: free
    previewPlan: starter
    # # #
    rootDir: apps/zipper.run
    buildFilter:
      paths:
        - apps/zipper.run/**/*
        - packages/**/*
      ignoredPaths:
        - '**/*.test.ts'
        - '**/*.test.tsx'
    buildCommand: 'yarn install; yarn env:inject:preview -- -- yarn build'
    startCommand: 'yarn start:preview'
    # # #
    envVars:
      - fromGroup: zipper-env-group--preview
      - key: DATABASE_URL
        fromDatabase:
          name: zipper-db--preview
          property: connectionString
      - key: REDIS_HOST
        fromService:
          type: redis
          name: zipper-redis--preview
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: zipper-redis--preview
          property: port
      - key: PUBLICLY_ACCESSIBLE_RPC_HOST
        fromService:
          name: zipper.dev--preview
          type: web
          property: host
      - key: NEXT_PUBLIC_ZIPPER_DOT_DEV_HOST
        fromService:
          name: zipper.dev--preview
          type: web
          property: host
      - key: NEXT_PUBLIC_ZIPPER_DOT_RUN_HOST
        fromService:
          name: zipper.run--preview
          type: web
          property: host

  # # # REDIS # # #
  - type: redis
    name: zipper-redis--preview
    plan: free
    previewPlan: starter
    ipAllowList: []

databases:
  - name: zipper-db--preview
    plan: free
    previewPlan: starter
