import { readFile } from 'fs/promises';
import type { NextApiRequest, NextApiResponse } from 'next';
import { readFrameworkFile } from '~/utils/read-framework-file';

const DENO = 'deno.d.ts';
const ZIPPER = 'zipper.d.ts';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse,
) {
  switch (req.query.filename as string) {
    case DENO: {
      // This is generated by running the following command:
      // deno types > deno.d.ts
      const src = await readFile('src/types/deno.d.ts', 'utf8');
      return res.setHeader('Content-Type', 'text/typescript').send(src);
    }
    case ZIPPER: {
      const src = await readFrameworkFile('types.d.ts');
      return res.setHeader('Content-Type', 'text/typescript').send(src);
    }
    default: {
      return res.status(404).send('404 Not Found');
    }
  }
}
