/**
 * 🦕
 * Please refrain from importing anything into this utility to keep it Deno-compatible
 */

const IMPORTS_REG_EXP = new RegExp(
  '/// <generated-imports[\\d\\D]*?/generated-imports>',
  'g',
);

const EXPORTS_REG_EXP = new RegExp(
  '/// <generated-exports[\\d\\D]*?/generated-exports>',
  'g',
);

function getExportNameFromFilename(filename: string) {
  const parts = filename.split('.');
  parts.pop();
  return parts
    .join('.')
    .toLowerCase()
    .replace(/[^a-zA-Z0-9]+(.)/g, (m, chr) => chr.toUpperCase());
}

export function generateModForFramework({
  code,
  filenames,
}: {
  code: string;
  filenames: string[];
}) {
  const generatedImports = [
    '/// <generated-imports>',
    '/// 🛑 DO NOT MODIFY THIS PART ///',
    '/// GENERATED BY packages/@zipper-utils/src/utils/generate-for-framework.ts',
    ...filenames.map((f, i) => `import * as module${i} from '../src/${f}';`),
    '/// </generated-imports>',
  ].join(`\n`);

  const generatedExports = [
    '/// <generated-exports>',
    '/// 🛑 DO NOT MODIFY THIS PART ///',
    '/// GENERATED BY packages/@zipper-utils/src/utils/generate-for-framework.ts',
    ...filenames.map(
      (f, i) => `'${f.replace(/\.(ts|tsx)$|$/, '.ts')}': module${i},`,
    ),
    '/// </generated-exports>',
  ].join('\n');

  return code
    .replace(IMPORTS_REG_EXP, generatedImports)
    .replace(EXPORTS_REG_EXP, generatedExports);
}

export function generateIndexForFramework({
  code,
  filenames: allFilenames,
}: {
  code: string;
  filenames: string[];
}) {
  // Filter out main since it's hardcoded
  const filenames = allFilenames.filter((f) => f !== 'main.ts');

  const generatedImports = [
    '/// <generated-imports>',
    '/// 🛑 DO NOT MODIFY THIS PART ///',
    '/// GENERATED BY packages/@zipper-utils/src/utils/generate-for-framework.ts',
    ...filenames.map((f, i) => `import * as module${i} from '../src/${f}';`),
    '/// </generated-imports>',
  ].join(`\n`);

  const generatedExports = [
    '/// <generated-exports>',
    '/// 🛑 DO NOT MODIFY THIS PART ///',
    '/// GENERATED BY packages/@zipper-utils/src/utils/generate-for-framework.ts',
    ...filenames.map(
      (f, i) => `'${f.replace(/\.(ts|tsx)$|$/, '.ts')}': module${i},`,
    ),
    '/// </generated-exports>',
  ].join('\n');

  return code
    .replace(IMPORTS_REG_EXP, generatedImports)
    .replace(EXPORTS_REG_EXP, generatedExports);
}
